forgeos:
  admin:
    menu:
      dashboard:
        url: /admin/dashboard
        html:
          class: left first
      users:
        url: /admin/users
        html:
         class: left
      statistics:
        url: /admin/statistics
        html:
          class: right

    submenu:
      administration:
        url:
          - /admin/administrators
          - /admin/roles
          - /admin/rights
        html:
          class: left first
        children:
          administrators: /admin/administrators
          roles: /admin/roles
          rights: /admin/rights
          import: /admin/import
          cachings: /admin/cachings
      settings:
        url: /admin/setting
        html:
          class: left
      library:
        url:
          - /admin/library
          - /admin/images/attachments
          - /admin/pdf/attachments
          - /admin/audio/attachments
          - /admin/video/attachments
          - /admin/media/attachments
          - /admin/doc/attachments
        html:
          class: left
      accounts:
        url: /admin/account
        html:
          class: left
      logout:
        url: /admin/logout
        html:
          class: right
      support:
        url: http://www.webpulser.com
        html:
          class: right first
