forgeos:
  admin:
    menu:
      dashboard:
        url: /admin/dashboard
        html:
          class: left first
      customers:
        url: /admin/users
        html:
         class: left
        children:
          users: /admin/users
      statistics:
        url: /admin/statistics
        html:
          class: right

    submenu:
      administration:
        url: /admin/administrators
        html:
          class: left first
        children:
          administrators:
            url: /admin/administrators
            children:
              roles: /admin/roles
              rights: /admin/rights
          import: /admin/import
          cachings: /admin/cachings
      settings:
        url: /admin/setting
        html:
          class: left
      library:
        url: /admin/pictures
        html:
          class: left
        children:
          pictures: /admin/pictures
          pdfs: /admin/pdfs
          audios: /admin/audios
          videos: /admin/videos
          media: /admin/media
          docs: /admin/docs
      accounts:
        url: /admin/account
        html:
          class: left
      logout:
        url: /admin/logout
        html:
          class: right
      support:
        url: http://www.webpulser.com
        html:
          class: right first
