forgeos:
  admin:
    menu:
      dashboard:
        url:
          - forgeos_core
          - :admin
          - :dashboard
        icon: dashboard
      customers:
        url:
          - forgeos_core
          - :admin
          - :users
        icon: user
      statistics:
        url:
          - forgeos_core
          - :admin
          - :statistics
        icon: bar-chart
    submenu:
      administration:
        url: '#'
        children:
          administrators:
            url:
              - forgeos_core
              - :admin
              - :administrators
            icon: user-md
          roles:
            url:
              - forgeos_core
              - :admin
              - :roles
            icon: pushpin
          rights:
            url:
              - forgeos_core
              - :admin
              - :rights
            icon: legal
          settings:
            url:
              - forgeos_core
              - :admin
              - :setting
            icon: cogs
          import:
            url:
              - forgeos_core
              - :admin
              - :import
            icon: download-alt
          cachings:
            url:
              - forgeos_core
              - :admin
              - :cachings
            icon: sitemap
      library:
        url: '#'
        children:
          pictures:
            url:
              - forgeos_core
              - :admin
              - :pictures
            icon: picture
          pdfs:
            url:
              - forgeos_core
              - :admin
              - :pdfs
            icon: book
          audios:
            url:
              - forgeos_core
              - :admin
              - :audios
            icon: music
          videos:
            url:
              - forgeos_core
              - :admin
              - :videos
            icon: film
          media:
            url:
              - forgeos_core
              - :admin
              - :media
            icon: file
          docs:
            url:
              - forgeos_core
              - :admin
              - :docs
            icon: briefcase
      account:
        url: '#'
        children:
          accounts:
            url:
              - forgeos_core
              - :admin
              - :account
            icon: user
          logout:
            url:
              - forgeos_core
              - :admin
              - :logout
            icon: signout
