require
  shim:
    'jquery_ujs': ['jquery']
    'bootstrap-all': ['jquery']
    'bootstrap-alert': ['jquery']
    'bootstrap-button': ['jquery']
    'bootstrap-carousel': ['jquery']
    'bootstrap-collapse': ['jquery']
    'bootstrap-dropdown': ['jquery']
    'bootstrap-modal': ['jquery']
    'bootstrap-scrollspy': ['jquery']
    'bootstrap-tab': ['jquery']
    'bootstrap-tooltip': ['jquery']
    'bootstrap-popover': ['jquery', 'bootstrap-tooltip']
    'bootstrap-transition': ['jquery']
    'bootstrap-typeahead': ['jquery']
    'forgeos/jqueryui/jquery.ui.core': ['jquery']
    'forgeos/jqueryui/jquery.ui.accordion': ['./jquery.ui.core','./jquery.ui.widget']
    'forgeos/jqueryui/jquery.ui.autocomplete': ['./jquery.ui.core', './jquery.ui.widget', './jquery.ui.position']
    'forgeos/jqueryui/jquery.ui.button': ['./jquery.ui.core','./jquery.ui.widget']
    'forgeos/jqueryui/jquery.ui.datepicker': ['./jquery.ui.core']
    'forgeos/jqueryui/jquery.ui.dialog': ['./jquery.ui.button', './jquery.ui.draggable', './jquery.ui.resizable']
    'forgeos/jqueryui/jquery.ui.draggable': ['./jquery.ui.mouse']
    'forgeos/jqueryui/jquery.ui.droppable': ['./jquery.ui.draggable']
    'forgeos/jqueryui/jquery.ui.mouse': ['./jquery.ui.core', './jquery.ui.widget']
    'forgeos/jqueryui/jquery.ui.positon': ['jquery']
    'forgeos/jqueryui/jquery.ui.progressbar': ['./jquery.ui.core', './jquery.ui.widget']
    'forgeos/jqueryui/jquery.ui.resizable': ['./jquery.ui.mouse']
    'forgeos/jqueryui/jquery.ui.selectable': ['./jquery.ui.mouse']
    'forgeos/jqueryui/jquery.ui.slider': ['./jquery.ui.mouse']
    'forgeos/jqueryui/jquery.ui.sortable': ['./jquery.ui.mouse']
    'forgeos/jqueryui/jquery.ui.tabs': ['./jquery.ui.core', './jquery.ui.widget']
    'forgeos/jqueryui/jquery.ui.widget': ['jquery']
    'forgeos/jqueryui/jquery.effects.core': ['jquery']
    'forgeos/jqueryui/jquery.effects.explode': ['./jquery.effects.core']
    'jquery.dataTables.min': ['jquery']
    'jquery.dataSlides': ['jquery']
  paths:
    'forgeos/jqueryui' : 'jqueryui'
